### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by jenskutilek** [xxyxyz/flat#1]
Thank you for this great module, it is really useful!

Do you have any plans for a full Python 3 version? I tried to port it myself, but the PNG adaptive filtering code is giving me headaches. Haven’t even looked at the JPEG module yet ...

https://github.com/jenskutilek/flat/tree/py3

**Comment by sukop** [comment]
Thank you for the kind words!

Yes, the next version will support Python 3 and I plan to release it sometime during the summer. I was somewhat bound by Python 3 support in PyPy but they are improving it every day so it starts to make sense to do the switch.

**Comment by jenskutilek** [comment]
Thanks! I’ll wait, it’s not super urgent for me.

**Comment by madig** [comment]
Is the Python 3 work public? How far have you come?

**Comment by sukop** [comment]
I have not yet started. It will be public, of course.

**Comment by davelab6** [comment]
https://github.com/xxyxyz/flat/compare/master...michielkauwatjoe:master is also a start in this direction

**Comment by sukop** [comment]
Should be fixed in https://github.com/xxyxyz/flat/commit/0c819333dd5b17a9e23077f1194a67b4b491eedf, sorry it took so long.

**Comment by davelab6** [comment]
🎉🎉🎉🎉

**Comment by jenskutilek** [comment]
Thank you very much for your work! I update the flat module in my [RoboChrome](https://github.com/jenskutilek/RoboChrome) extension.
