### ISSUE TITLE
Where can we find examples?

### ISSUE THREAD

**Issue by villares** [xxyxyz/flat#12]
I believe one of the best ways to learn a a tool is to look at some examples. There may be some evidence to support that it helps (https://dl.acm.org/doi/10.1145/1151588.1151608).

Is there an example repository for `flat`somewhere?

My first contribution, and perhaps my only meaningful contribution to an open-source project, has been working on documentation, I started by porting examples from Processing Java to Processing Python mode. And I would like to contribute, if possible.

**Comment by sukop** [comment]
There is none! Truth is, I never thought there will be a need for it but since you are asking there clearly is. The problem is, I don't know how to proceed. Should I host a wiki for the documentation? Should there be a separate "flat-examples" repository with a collection of simple examples? Should there a be "book" introducing various concepts with increasing complexity? Should each method in API reference get an illustrating example? I have to think about it, if you (or anyone else reading this) have any ideas I'm all ears.

**Comment by villares** [comment]
Every and each of your mentioned ideas is a good one, but they have different energy requirements for the maintainer. I really think a healthy project should have some kind of community around it, and that will certainly help produce examples (if you encourage people to contribute).

Please do not take this as harsh criticism, but as it is now it makes it very hard for me to adopt `flat` with my students. I have tried for many hours to make use of the path clipping methods (something that I really would love to have, as it is something missing from Processing and one has to use things like Geomerative that are very hard to explain to novices) and I ended up feeling stupid and frustrated.

A reference with a small example for each method is kind of essential to bring people in. I'm sure you are aware of https://py.processing.org/reference/ 

As for where to put the examples collection, it could be just a folder at this repository, or you could add them to the library package and have a fancy command line interface to run them, or you could create a separate repo if you feel like it would "polute" the library main repo. It really doesn't matter as far as it is linked from a central place to make it "discoverable".

I quite like the wiki idea, there is even a GitHub based tool that seems a bit ugly but could work (and it could be started with low effort).

Thank you again for your generous code and attention.

**Comment by ynx0** [comment]
@sukop I also would love some examples. I read all the articles on the original website ages ago, and while the results really appealed to me, I had no way of knowing how to start quickly, so I kinda gave up without trying. 

I think that the simplest and lowest energy option which would still be useful would be to just upload a few (4-5) different examples that cover a broad surface of the API. Even without comments, as long as we can run the examples and they are simple enough to tinker with, it would suffice.

Edit: same goes for `xxyxyz/even`, although idk if that's still maintained.

**Comment by sukop** [comment]
@villares @ynx0 I've just created [flat-examples](https://github.com/xxyxyz/flat-examples), please let me know what you think.

**Comment by villares** [comment]
Woderful!
