### ISSUE TITLE
Project boilerplate?

### ISSUE THREAD

**Issue by madig** [xxyxyz/flat#2]
Hi! This looks promising, however: there is no build system boilerplate like a `setup.py` or `pyproject.toml` for using Poetry or Flit, no tests and no CI integration for easy commit-test-deploy workflows -- do you have something already or are you interested in getting something set up?

**Comment by sukop** [comment]
Sorry for late reply, I was off-line for few days.

No, not really interested (yet). There are much more pressing issues than the boilerplate and the project is still quite small. I'll add `setup.py` I use for PyPI in the next release, thanks for the suggestion.
