### ISSUE TITLE
Readme should be made PyPI-friendly

### ISSUE THREAD

**Issue by madig** [xxyxyz/flat#5]
https://packaging.python.org/guides/making-a-pypi-friendly-readme/

This will help with presenting the library in a more polished way on PyPI. Making it a Markdown-flavored Readme will also make it render better here on GitHub.

**Comment by sukop** [comment]
The title is misleading as it implies the readme is not PyPI friendly (which it is, as seen in the link you included). As written it also renders here the same way as before as GitHub auto-parses URLs in plain-text readmes.

This is similar to what we discussed before: how is changing `.txt` to `.md` and adding more logic to `setup.py` any better than copy-pasting three sentences to `long_description`? Especially when it was working just fine, the commit does not present any visible change, and the project description will not change in foreseeable future, if at all?

**Comment by madig** [comment]
The change is about making the Readme parse as Markdown. GitHub displays txt files plainly with a monospaced font. Making it Markdown enables nice formatting, for when you might want to expand the information to e.g. include contribution guidelines etc. (see https://github.com/googlefonts/fontbakery for a long example). The `long_description` is used by PyPI to display information on a package, see https://docs.python.org/3/distutils/packageindex.html#pypi-package-display. black does it and what you see on https://pypi.org/project/black/ is the readme in the git repo.

This essentially allows you to write a readme once and have it nicely displayed on GitHub an PyPI.

**Comment by sukop** [comment]
My question was about why to add complexity for a readme which currently reads three sentences. Once it becomes more rich, it will make sense to use Markdown, not the other way around. Of course, then it will compete with project's website (which uses Markdown, btw.). And good that you bring Black up again: apparently, they don't have a dedicated website so a detailed readme makes sense, whereas Flat has a site.

**Comment by sukop** [comment]
It might not look that way but I truly appreciate the effort, thank you!
